version: '3.8'
services:
 webhook_server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - KAVENEGAR_API_KEY=
      - RECEPTOR_FILE_PATH=/app/receptors.txt
    volumes:
      - ./receptors.txt:/app/receptors.txt
